// <auto-generated />
namespace BureauAppServiceService.Migrations.Business
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialBusiness1Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialBusiness1Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201607250706469_InitialBusiness1Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
